# Generated by Django 4.2.4 on 2023-09-04 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-name'], 'verbose_name': 'Enlace', 'verbose_name_plural': 'Enlaces'},
        ),
    ]
